### PR TITLE
Always acquire lock for updating given document

### LINKED ISSUE #112: Concurrently using db.Update()
I get sometimes following error from Update():

    Document `2172066362944826002` is locked for update - try again later

I wonder what is suggested handling of it?

### PR DESCRIPTION
**Pull request by Komosa**
- simplify code for access of given document;
- simplify concurrent update;
- greatly improve possibility for further update improvements (#111);
- fix #112;
- does not decrease performance of `tiedot -mode=bench` on my machine.

### CODE REVIEW

**Comment by gertcuykens** [comment]
looks good to me waiting for @HouzuoGuo

**Comment by HouzuoGuo** [comment]
Wow, thanks a lot! I'll take a look tomorrow and get back to you.

**Comment by HouzuoGuo** [comment]
Very well done, I'm measuring 10% performance improvements in update and delete benchmarks.

**Comment by HouzuoGuo** [comment]
I added you to the collaborators list, feel free to shape the project however you like.

**Pull request merged**
